steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/l1-team-testing/responsive-travel-website:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/l1-team-testing/responsive-travel-website:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app'
        'deploy',
        'gcr.io/l1-team-testing/responsive-travel-website',
        '--image=gcr.io/l1-team-testing/gcr.io/l1-team-testing/responsive-travel-website:$SHORT_SHA',
        '--region=us-central1',
        '--project=l1-team-testing',
	      '--quiet'

      ]



options:
  logging: CLOUD_LOGGING_ONLY

